site_name: Test docs
site_description: 'A docs test'
site_author: 'Karl Martin Sola'
docs_dir: docs/
repo_name: 'tasta-no/grc'
repo_url: 'https://github.com/tasta-no/grc'
theme:
  name: 'material'
nav:
    - Home: 'Readme.md'
    - 'ISMS':
        - 'Security Requirements': 'security-requirements.md'
