site_name: Test docs
site_description: 'A docs test'
site_author: 'Karl Martin Sola'
docs_dir: docs/
repo_name: 'tasta-no/grc'
repo_url: 'https://github.com/tasta-no/grc'
theme:
  name: 'material'
nav:
    - Home: 'Readme.md'
    - 'Management System':
        - 'Security Requirements': 'security-requirements.md'
    - 'Cyber security awareness':
        - 'IT Security': 'docs/awareness/it-security.md'
        - 'Threat landscape': 'docs/awareness/threat-landscape.md'
