nav:
    - Home: 'README.md'
    - 'Information Security':
        - 'Change requests': '/information-security/change-requests.md'
        - 'Introduction': '/information-security/introduction.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
