site_name: Test docs
site_description: 'A docs test'
site_author: 'Karl Martin Sola'
docs_dir: docs/
repo_name: 'tasta-no/grc'
repo_url: 'https://github.com/tasta-no/grc'
theme:
  name: 'material'
  features:
    - navigation.tabs
#nav:
#    - Home: 'Readme.md'
#    - 'Management System':
#        - 'Security Requirements': 'itsm/security-requirements.md'
#    - 'Cyber security awareness':
#        - 'IT Security': 'awareness/it-security.md'
#        - 'Threat landscape': 'awareness/threat-landscape.md'
